# Generated by Django 6.0.4 on 2026-05-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Mineral Categories',
            },
        ),
        migrations.CreateModel(
            name='MiningConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='J&N Mining', max_length=200)),
                ('tagline', models.CharField(default='Extracting Value From the Earth', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mining/brand/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='mining/brand/')),
                ('primary_color', models.CharField(default='#B45309', help_text='Hex e.g. #B45309', max_length=7)),
                ('accent_color', models.CharField(default='#78350F', help_text='Hex e.g. #78350F', max_length=7)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('hero_heading', models.CharField(default='Industrial Mining Excellence', max_length=300)),
                ('hero_sub', models.TextField(default='Responsible mineral extraction and processing in Malawi.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='mining/hero/')),
                ('about_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='mining/about/')),
                ('years_exp', models.PositiveIntegerField(default=1)),
                ('tonnes_mined', models.CharField(blank=True, help_text='e.g. 50,000+', max_length=50)),
                ('sites', models.PositiveIntegerField(default=1)),
                ('compliance_text', models.TextField(blank=True, help_text='Environmental & safety certifications')),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Mining Site Config',
                'verbose_name_plural': 'Mining Site Config',
            },
        ),
        migrations.CreateModel(
            name='MiningEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mining/equipment/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MineralProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('specifications', models.TextField(blank=True, help_text='Grade, purity, size, chemical composition')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mining/minerals/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minerals', to='mining.mineralcategory')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MiningOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mining/operations/')),
                ('is_active', models.BooleanField(default=True)),
                ('minerals', models.ManyToManyField(blank=True, related_name='operations', to='mining.mineralproduct')),
            ],
        ),
    ]
