# Generated by Django 6.0.4 on 2026-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(choices=[('group', 'Group Landing'), ('products', 'Building Products'), ('construction', 'Construction'), ('mining', 'Mining'), ('timber', 'Timber'), ('general', 'General')], default='general', help_text='Which sub-site sent this enquiry', max_length=20),
        ),
    ]
