# Generated by Django 6.0.4 on 2026-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='J&N Building Products', max_length=200)),
                ('tagline', models.CharField(default='Make Your House Smile', max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('whatsapp_number', models.CharField(help_text='Include country code e.g. +265991234567', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('hero_heading', models.CharField(default="Building Malawi's Future", max_length=300)),
                ('hero_subheading', models.TextField(default='Quality building products and construction services you can trust.')),
                ('about_text', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('happy_clients', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g. Homeowner, Contractor', max_length=100)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
