# Generated by Django 6.0.4 on 2026-05-07 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Main image shown on the About page.', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission',
            field=models.TextField(blank=True, default='To provide affordable, high-quality building products and construction services that help Malawians build safe, beautiful, and lasting homes and structures.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_desc',
            field=models.TextField(default='We only supply products that meet high construction standards. No shortcuts.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_icon',
            field=models.CharField(default='bi-award-fill', help_text='Bootstrap icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_title',
            field=models.CharField(default='Quality First', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_desc',
            field=models.TextField(default='Your project goals drive everything we do. We listen before we build.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_icon',
            field=models.CharField(default='bi-people-fill', help_text='Bootstrap icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_title',
            field=models.CharField(default='Customer Focused', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_desc',
            field=models.TextField(default='Transparent pricing and honest communication — always. No hidden costs.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_icon',
            field=models.CharField(default='bi-shield-check-fill', help_text='Bootstrap icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_title',
            field=models.CharField(default='Integrity Always', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_vision',
            field=models.TextField(blank=True, default='To be the most trusted and preferred building products and construction company in Malawi — known for quality, reliability, and making every house smile.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_text',
            field=models.CharField(default='Trusted Building Partner in Malawi', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading_highlight',
            field=models.CharField(default="Malawi's", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading_prefix',
            field=models.CharField(default='Building', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading_suffix',
            field=models.CharField(default='Future', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload a hero background image. If left empty, the default static image will be used.', null=True, upload_to='hero/'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Page visited', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_type', models.CharField(blank=True, default='', max_length=20)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_visito_created_1532f8_idx'), models.Index(fields=['ip_address'], name='core_visito_ip_addr_aa43f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_clicks', to='contacts.contactmessage')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_clicks', to='products.product')),
            ],
            options={
                'verbose_name': 'WhatsApp Click',
                'verbose_name_plural': 'WhatsApp Clicks',
                'ordering': ['-created_at'],
            },
        ),
    ]
