# Generated by Django 5.2.7 on 2026-05-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitor_whatsappclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_text',
            field=models.CharField(default='Trusted Building Partner in Malawi', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading_highlight',
            field=models.CharField(default="Malawi's", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading_prefix',
            field=models.CharField(default='Building', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading_suffix',
            field=models.CharField(default='Future', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload a hero background image. If left empty, the default static image will be used.', null=True, upload_to='hero/'),
        ),
    ]
