# Generated by Django 6.0.4 on 2026-05-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_about_image_sitesettings_about_mission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='J&N Group of Companies', max_length=200)),
                ('tagline', models.CharField(default='Industrial Excellence For The Future', max_length=300)),
                ('sub_tagline', models.CharField(default='Construction · Mining · Manufacturing', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='group/brand/')),
                ('hero_image', models.ImageField(blank=True, help_text='Full-screen background image for the hero', null=True, upload_to='group/hero/')),
                ('hero_video_url', models.URLField(blank=True, help_text='Optional YouTube embed ID for background video')),
                ('btn1_label', models.CharField(default='Blue Rock Wall Putty', max_length=100)),
                ('btn1_url', models.CharField(default='/products/', max_length=200)),
                ('btn1_icon', models.CharField(default='bi-droplet-fill', max_length=60)),
                ('btn2_label', models.CharField(default='Construction Company', max_length=100)),
                ('btn2_url', models.CharField(default='/construction/', max_length=200)),
                ('btn2_icon', models.CharField(default='bi-building', max_length=60)),
                ('btn3_label', models.CharField(default='Mining Company', max_length=100)),
                ('btn3_url', models.CharField(default='/mining/', max_length=200)),
                ('btn3_icon', models.CharField(default='bi-gem', max_length=60)),
                ('story_heading', models.CharField(default='About the Group', max_length=200)),
                ('story_text', models.TextField(default='J&N Group of Companies is a diversified industrial group based in Malawi, delivering excellence across building products, construction, and mining.')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Group Site Config',
                'verbose_name_plural': 'Group Site Config',
            },
        ),
    ]
