# Generated by Django 5.2.7 on 2026-05-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_hero_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Main image shown on the About page.', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission',
            field=models.TextField(blank=True, default='To provide affordable, high-quality building products and construction services that help Malawians build safe, beautiful, and lasting homes and structures.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_desc',
            field=models.TextField(default='We only supply products that meet high construction standards. No shortcuts.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_icon',
            field=models.CharField(default='bi-award-fill', help_text='Bootstrap icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_title',
            field=models.CharField(default='Quality First', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_desc',
            field=models.TextField(default='Your project goals drive everything we do. We listen before we build.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_icon',
            field=models.CharField(default='bi-people-fill', help_text='Bootstrap icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_title',
            field=models.CharField(default='Customer Focused', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_desc',
            field=models.TextField(default='Transparent pricing and honest communication — always. No hidden costs.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_icon',
            field=models.CharField(default='bi-shield-check-fill', help_text='Bootstrap icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_title',
            field=models.CharField(default='Integrity Always', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_vision',
            field=models.TextField(blank=True, default='To be the most trusted and preferred building products and construction company in Malawi — known for quality, reliability, and making every house smile.'),
        ),
    ]
