# Generated by Django 6.0.4 on 2026-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groupconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconfig',
            name='btn4_icon',
            field=models.CharField(default='bi-tree-fill', max_length=60),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='btn4_label',
            field=models.CharField(default='Timber Company', max_length=100),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='btn4_url',
            field=models.CharField(default='/timber/', max_length=200),
        ),
    ]
