# Generated by Django 5.2.7 on 2026-05-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_groupconfig_btn4_icon_groupconfig_btn4_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconfig',
            name='btn1_desc',
            field=models.CharField(default='Extracting value. Powering progress.', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='btn2_desc',
            field=models.CharField(default='Building structures. Creating tomorrow.', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='btn3_desc',
            field=models.CharField(default='Sustainable timber. Stronger communities.', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='btn4_desc',
            field=models.CharField(default='Quality products like Blue Rock Wall Putty for durable finishes.', max_length=200),
        ),
    ]
