# Generated by Django 5.2.7 on 2026-05-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupconfig_btn1_desc_groupconfig_btn2_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconfig',
            name='btn1_short',
            field=models.CharField(default='BUILDING PRODUCTS', help_text='Short uppercase label for card', max_length=30),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='btn2_short',
            field=models.CharField(default='CONSTRUCTION', help_text='Short uppercase label for card', max_length=30),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='btn3_short',
            field=models.CharField(default='MINING', help_text='Short uppercase label for card', max_length=30),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='btn4_short',
            field=models.CharField(default='TIMBER', help_text='Short uppercase label for card', max_length=30),
        ),
        migrations.AlterField(
            model_name='groupconfig',
            name='btn1_desc',
            field=models.CharField(default='Quality products like Blue Rock Wall Putty for durable finishes.', max_length=200),
        ),
        migrations.AlterField(
            model_name='groupconfig',
            name='btn3_desc',
            field=models.CharField(default='Extracting value. Powering progress.', max_length=200),
        ),
        migrations.AlterField(
            model_name='groupconfig',
            name='btn4_desc',
            field=models.CharField(default='Sustainable timber. Stronger communities.', max_length=200),
        ),
    ]
