# Generated by Django 5.2.7 on 2026-05-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_groupconfig_btn1_short_groupconfig_btn2_short_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupconfig',
            name='btn1_desc',
        ),
        migrations.RemoveField(
            model_name='groupconfig',
            name='btn1_short',
        ),
        migrations.RemoveField(
            model_name='groupconfig',
            name='btn2_desc',
        ),
        migrations.RemoveField(
            model_name='groupconfig',
            name='btn2_short',
        ),
        migrations.RemoveField(
            model_name='groupconfig',
            name='btn3_desc',
        ),
        migrations.RemoveField(
            model_name='groupconfig',
            name='btn3_short',
        ),
        migrations.RemoveField(
            model_name='groupconfig',
            name='btn4_desc',
        ),
        migrations.RemoveField(
            model_name='groupconfig',
            name='btn4_short',
        ),
    ]
