# Generated by Django 5.2.7 on 2026-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_groupconfig_btn1_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconfig',
            name='card1_bg_image',
            field=models.ImageField(blank=True, help_text='Background image for Building Products card', null=True, upload_to='group/cards/'),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='card1_description',
            field=models.TextField(default='Blue Rock Wall Putty & premium finishes.', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='card2_bg_image',
            field=models.ImageField(blank=True, help_text='Background image for Construction card', null=True, upload_to='group/cards/'),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='card2_description',
            field=models.TextField(default='Building structures, engineering the future.', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='card3_bg_image',
            field=models.ImageField(blank=True, help_text='Background image for Mining card', null=True, upload_to='group/cards/'),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='card3_description',
            field=models.TextField(default='Extracting value, powering industrial progress.', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='card4_bg_image',
            field=models.ImageField(blank=True, help_text='Background image for Timber card', null=True, upload_to='group/cards/'),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='card4_description',
            field=models.TextField(default='Sustainable forestry & wood solutions.', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='divider_subtitle',
            field=models.CharField(default="Engineering Malawi's infrastructure & economy", max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='divider_title',
            field=models.CharField(default='Unmatched Industrial Strength', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='footer_copyright',
            field=models.CharField(default='Industrial Excellence.', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='hero_subheading',
            field=models.CharField(default='Mining · Construction · Timber · Building Products', max_length=300),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='hero_title',
            field=models.CharField(default="Building Today.<br><span class='orange-text'>Empowering Tomorrow.</span>", help_text="Use <br> for line break, and <span class='orange-text'> for orange highlights.", max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='stat1_label',
            field=models.CharField(default='Strategic Sectors', max_length=100),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='stat1_number',
            field=models.PositiveIntegerField(default=4, help_text='Number for first stat'),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='stat2_label',
            field=models.CharField(default='Years Excellence', max_length=100),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='stat2_number',
            field=models.PositiveIntegerField(default=12, help_text='Number for second stat'),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='stat3_label',
            field=models.CharField(default='Industry Partners', max_length=100),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='stat3_number',
            field=models.PositiveIntegerField(default=250, help_text='Number for third stat'),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value1_desc',
            field=models.CharField(default='Four industries, one united vision', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value1_icon',
            field=models.CharField(default='bi-gear-wide-connected', max_length=50),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value1_title',
            field=models.CharField(default='Diverse Expertise', max_length=100),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value2_desc',
            field=models.CharField(default='Highest international standards', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value2_icon',
            field=models.CharField(default='bi-shield-check', max_length=50),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value2_title',
            field=models.CharField(default='Quality & Safety', max_length=100),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value3_desc',
            field=models.CharField(default='Responsible industrial growth', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value3_icon',
            field=models.CharField(default='bi-recycle', max_length=50),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value3_title',
            field=models.CharField(default='Sustainability', max_length=100),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value4_desc',
            field=models.CharField(default='Engineering modern Africa', max_length=200),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value4_icon',
            field=models.CharField(default='bi-cpu', max_length=50),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='value4_title',
            field=models.CharField(default='Innovation', max_length=100),
        ),
    ]
