# Generated by Django 5.2.7 on 2026-05-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_groupconfig_card1_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupconfig',
            name='group_name',
            field=models.CharField(default='J&N Pvt Limited', max_length=200),
        ),
    ]
