# Generated by Django 5.2.7 on 2026-05-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_groupconfig_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupconfig',
            name='hero_video_url',
            field=models.CharField(blank=True, help_text='YouTube video ID (e.g., dQw4w9WgXcQ). Leave empty to use hero_image.', max_length=50),
        ),
    ]
