# Generated by Django 5.2.7 on 2026-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_groupconfig_hero_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='source',
            field=models.CharField(choices=[('group', 'Group Landing'), ('products', 'Building Products'), ('construction', 'Construction'), ('mining', 'Mining'), ('timber', 'Timber'), ('general', 'General')], default='general', help_text='Which sub-site this testimonial is for', max_length=20),
        ),
    ]
