# Generated by Django 6.0.4 on 2026-05-10 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Timber Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimberProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='timber/projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='J&N Timber', max_length=200)),
                ('tagline', models.CharField(default='Sustainable Timber, Expertly Processed', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='timber/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='timber/brand/')),
                ('primary_color', models.CharField(default='#166534', help_text='Hex e.g. #166534 (Forest Green)', max_length=7)),
                ('accent_color', models.CharField(default='#78350F', help_text='Hex e.g. #78350F (Brown)', max_length=7)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('hero_heading', models.CharField(default='Premium Timber & Wood Processing', max_length=300)),
                ('hero_sub', models.TextField(default='From forest to finished product — quality timber for every project.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='timber/hero/')),
                ('about_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='timber/about/')),
                ('years_exp', models.PositiveIntegerField(default=1)),
                ('trees_processed', models.CharField(blank=True, help_text='e.g. 50,000+', max_length=50)),
                ('clients', models.PositiveIntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Timber Site Config',
                'verbose_name_plural': 'Timber Site Config',
            },
        ),
        migrations.CreateModel(
            name='TimberProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('specifications', models.TextField(blank=True, help_text='Species, dimensions, grade, moisture content, treatment')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timber/products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='timber.timbercategory')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
