# Generated by Django 6.0.4 on 2026-05-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='J&N Construction', max_length=200)),
                ('tagline', models.CharField(default='Building Tomorrow, Today', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='construction/brand/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='construction/brand/')),
                ('primary_color', models.CharField(default='#1A56DB', help_text='Hex e.g. #1A56DB', max_length=7)),
                ('accent_color', models.CharField(default='#0C2D6B', help_text='Hex e.g. #0C2D6B', max_length=7)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('hero_heading', models.CharField(default='Building Excellence', max_length=300)),
                ('hero_sub', models.TextField(default='Professional construction services across Malawi.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='construction/hero/')),
                ('hero_video_url', models.URLField(blank=True, help_text='Optional YouTube/Vimeo background video URL')),
                ('about_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='construction/about/')),
                ('years_exp', models.PositiveIntegerField(default=1)),
                ('projects_done', models.PositiveIntegerField(default=0)),
                ('clients', models.PositiveIntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Construction Site Config',
                'verbose_name_plural': 'Construction Site Config',
            },
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, help_text='e.g. MK 50 million', max_length=100)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='construction/projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-building', help_text='Bootstrap icon class', max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='construction/services/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='construction/team/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction/project_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='construction.constructionproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
