# Generated by Django 5.2.7 on 2026-05-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Construction, Mechanical, Architecture', max_length=100)),
                ('description', models.TextField(help_text='Short paragraph shown on the fact card')),
                ('image', models.ImageField(help_text='Background image for this card', upload_to='construction/facts/')),
                ('number', models.PositiveIntegerField(default=1, help_text='Display number like 01, 02, 03...')),
                ('link_url', models.CharField(blank=True, help_text='e.g. /construction/services/', max_length=200)),
                ('link_text', models.CharField(default='READ MORE', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Construction Fact',
                'verbose_name_plural': 'Construction Facts',
                'ordering': ['order', 'number'],
            },
        ),
    ]
