# Generated by Django 5.2.7 on 2026-05-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_constructionfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionconfig',
            name='page_header_image',
            field=models.ImageField(blank=True, help_text='Background image for all inner pages (About, Services, Projects, Contact).', null=True, upload_to='construction/page_headers/'),
        ),
    ]
