# Generated by Django 6.0.4 on 2026-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Blue Rock Wall Putty', max_length=200)),
                ('tagline', models.CharField(default='Smoothest Finish, Strongest Walls', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='products/logo/')),
                ('hero_heading', models.CharField(default='Premium Wall Putty in Malawi', max_length=300)),
                ('hero_subheading', models.TextField(default='Quality wall putty for every surface.')),
                ('hero_badge_text', models.CharField(default='Trusted Since 2010', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='products/hero/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('about_text', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#C41230', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Building Products Config',
                'verbose_name_plural': 'Building Products Config',
            },
        ),
    ]
