# Generated by Django 5.2.7 on 2026-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_buildingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingsettings',
            name='primary_color',
            field=models.CharField(default='#1e3a8a', max_length=7),
        ),
    ]
