# Generated by Django 5.2.7 on 2026-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_buildingsettings_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating 0–5', max_digits=3),
        ),
    ]
